import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';

const root = resolve(import.meta.dirname, '..');
const html = readFileSync(resolve(root, 'dist/index.html'), 'utf8');
const css = readFileSync(resolve(root, 'dist/styles.css'), 'utf8');
const funnelHtml = readFileSync(resolve(root, 'dist/veterans/index.html'), 'utf8');
const funnelCss = readFileSync(resolve(root, 'dist/veterans/veterans.css'), 'utf8');
const funnelJs = readFileSync(resolve(root, 'dist/veterans/veterans.js'), 'utf8');
const booking = 'https://calendly.com/anvar-life/15min';
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]);
assert.equal(new Set(ids).size, ids.length, 'Duplicate HTML id');
const anchors = [...html.matchAll(/href="#([^"]+)"/g)].map(m => m[1]);
anchors.forEach(id => assert(ids.includes(id), `Missing target: ${id}`));
const localAssets = [...html.matchAll(/(?:src|href)="([^"#]+)"/g)].map(m => m[1]).filter(v => !/^(https?:|data:|mailto:|tel:)/.test(v));
localAssets.forEach(asset => assert(existsSync(resolve(root, 'dist', asset)), `Missing asset: ${asset}`));
const links = [...html.matchAll(/<a\b[^>]*href="(https:\/\/calendly.com\/[^\"]+)"[^>]*>/g)].map(m => m[1]);
assert(links.filter(v => v === booking).length >= 7, 'Expected repeated booking CTA');
links.forEach(url => assert([booking, 'https://calendly.com/privacy'].includes(url), `Unexpected Calendly link: ${url}`));
assert(!/1[,.]?000\+|high approval|guaranteed approval|discount expires/i.test(html), 'Unsubstantiated claim');
assert(html.includes('not affiliated with or endorsed by'), 'Missing VA affiliation disclosure');
assert(html.includes('22327730') && html.includes('(718) 308-6929'), 'Missing provided identity');
assert(html.includes('name="viewport"'), 'Missing responsive viewport');
assert(html.includes('name="robots" content="index,follow'), 'Public version should permit indexing');
assert(!/noindex|nofollow/i.test(html), 'Public version must not block indexing');
const canonicalMatch = html.match(/rel="canonical" href="(https:\/\/[^\"]+\/)"/);
assert(canonicalMatch, 'Missing absolute HTTPS canonical URL');
const canonical = canonicalMatch[1];
assert(html.includes(`property="og:url" content="${canonical}"`), 'Open Graph URL must match canonical');
const jsonLdMatch = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
assert(jsonLdMatch, 'Missing JSON-LD');
const jsonLd = JSON.parse(jsonLdMatch[1]);
assert.equal(jsonLd['@context'], 'https://schema.org');
assert(jsonLd['@graph'].some(item => item['@type'] === 'WebSite' && item.url === canonical), 'WebSite schema must match canonical');
assert(jsonLd['@graph'].some(item => item['@type'] === 'Person' && item.name === 'Anvar Baltakhojayev'), 'Missing Person schema');
const robots = readFileSync(resolve(root, 'dist/robots.txt'), 'utf8');
const sitemap = readFileSync(resolve(root, 'dist/sitemap.xml'), 'utf8');
assert(robots.includes('Allow: /') && robots.includes(`${canonical}sitemap.xml`), 'robots.txt must allow crawling and reference sitemap');
assert(sitemap.includes(`<loc>${canonical}</loc>`), 'Sitemap URL must match canonical');
assert(html.includes('aria-expanded') && html.includes('aria-controls'), 'Missing navigation accessibility');
assert(css.includes('prefers-reduced-motion'), 'Missing reduced motion support');
assert.equal((css.match(/\{/g)||[]).length, (css.match(/\}/g)||[]).length, 'Unbalanced CSS');
assert.equal((funnelCss.match(/\{/g)||[]).length, (funnelCss.match(/\}/g)||[]).length, 'Unbalanced funnel CSS');
const funnelIds = [...funnelHtml.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]);
assert.equal(new Set(funnelIds).size, funnelIds.length, 'Duplicate funnel HTML id');
const funnelAnchors = [...funnelHtml.matchAll(/href="#([^"]+)"/g)].map(m => m[1]);
funnelAnchors.forEach(id => assert(funnelIds.includes(id), `Missing funnel target: ${id}`));
assert(!/<video\b|href="#watch"|data-video-src|id="unlock-status"/.test(funnelHtml), 'No unfinished video or watch gate');
assert((funnelHtml.match(/data-booking-cta/g) || []).length >= 4, 'Direct booking must be repeated through the funnel');
assert(funnelHtml.includes('Veteran with Benefits') && html.includes('Veteran with Benefits'), 'Correct company name required');
assert(!/Benefits with Veterans/.test(html + funnelHtml), 'Outdated company name');
assert(funnelHtml.includes('https://calendly.com/privacy'), 'Funnel booking privacy disclosure required');
assert(funnelHtml.includes('An illustrative situation') && funnelHtml.includes('Not clients or endorsers'), 'Family examples must not imply testimonials');
const funnelAssets = [...funnelHtml.matchAll(/(?:src|href)="([^"#]+)"/g)].map(m => m[1]).filter(v => !/^(https?:|data:|mailto:|tel:)/.test(v));
funnelAssets.filter(asset => asset !== '/').forEach(asset => {
  const assetPath = asset.startsWith('/') ? resolve(root, 'dist', asset.slice(1)) : resolve(root, 'dist/veterans', asset);
  assert(existsSync(assetPath), `Missing funnel asset: ${asset}`);
});
assert(funnelHtml.includes('not affiliated with or endorsed by'), 'Missing funnel VA affiliation disclosure');
assert(funnelHtml.includes('NPN 22327730') && funnelHtml.includes('(718) 308-6929'), 'Missing funnel identity');
assert(!/guaranteed approval|VA[- ]discount|offer expires|limited time|access to every carrier|licensed with every carrier/i.test(funnelHtml), 'Misleading funnel claim');
assert(!/sessionStorage|localStorage|fetch\(/.test(funnelJs), 'Questionnaire answers must stay in page memory');
assert(funnelJs.includes('utm_campaign'), 'Campaign attribution handoff missing');
const manifest = JSON.parse(readFileSync(resolve(root, '.openai/hosting.json'), 'utf8'));
assert.equal(manifest.static.directory, 'dist');
console.log(JSON.stringify({ok:true,localAssets:localAssets.length,internalAnchors:anchors.length,bookingCTAs:links.filter(v=>v===booking).length,sections:ids.length,notes:'Static checks only. No test appointment created.'}));
